#!/bin/bash

#
# file:			run_under_invest
# path:			scripts/run_under_invest
# created by:	Davit Kalantaryan (davit.kalataryan@desy.de)
# created on:	2021 Nov 29
#
# the aim:		The role of this script is to start software 
#				under memory handling investigation
#


if [ $# -gt 0 ]; then
	PROG_NAME="$1"
	shift
	LD_PRELOAD=libcrash_investiator_new_malloc.so ${PROG_NAME} "$@"
else
	echo "Program name is not specified"
fi
